### ISSUE TITLE
Flash Collector Script相关

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#1]
location.href =location.href可以直接解决问
![4FIG~IJN4GUZQH5EED(UBVW](https://user-images.githubusercontent.com/84607814/169047314-a57358ab-e9f2-4b94-86f0-6db1039e5097.png)
题

**Comment by Cnotech** [comment]
哦我好像知道为什么了，草，4399这个操作令人窒息，谢谢你
