### ISSUE TITLE
无法自动下载没有以 .htm(l) 结尾的链接

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#10]
### Flash Collector 版本号

1.9

### Windows 版本

Windows 11 x64

### 发生什么事了？

我在添加对 7724 的支持时，当我输入没有以 .htm(l) 结尾的链接时（7724的小游戏链接都不带后缀名），游戏不会自动下载，点击右边的按钮后 跳转到百度搜索页面  

### 如何复现这个问题？

比如，当我输入 https://www.7724.com/JieXianMiTi2/ 后，我又把它改成 https://www.7724.com/JieXianMiTi2/xxx.htm ，游戏便开始自动下载（我的规则匹配了中间的JieXianMiTi2，然后生成合适的链接）

**Comment by Cnotech** [comment]
目前页面首先会检查用户输入内容是否是一个url，使用的正则表达式要求结尾为 `\.html? `，如果不满足这个正则就会被当成搜索内容打开搜索页。稍后会改进一下这个正则表达式。

**Comment by Cnotech** [comment]
已在主分支解决此问题
