### ISSUE TITLE
[fix]: 部分7k7k非规范页面无法解析

### ISSUE THREAD

**Issue by dx7organ** [Cnotech/flash-collector#12]
### 有何高见？

http://news.7k7k.com/mxw/zjwdssb.html  冒险王之神兵传奇终极无敌速升版 比4399多个法师职业 童年经典 谢谢作者了

**Comment by Cnotech** [comment]
二级域名news，不是游戏页面

**Comment by Cnotech** [comment]
增加对部分不规范7k7k页面的解析功能，自测配合智能嗅探+兼容模式已经可以正常运行。

可以先用这个预览版测试一下，如果有其他不规范页面还是没法解析的欢迎继续发 issue。

https://cloud.189.cn/web/share?code=nYJjU3bYjuQv （访问码：5c4d）

**Comment by Cnotech** [comment]
长时间无回复，故关闭此issue
