### ISSUE TITLE
[bug]: 昵称中包含的特殊字符无法解码

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#13]
### Flash Collector 版本号

1.9

### Windows 版本

Windows 11 x64

### 发生什么事了？

昵称中包含的特殊字符(比如`%3F (?)`)无法解码(解码后还有`%3F`)  
建议: 添加[cookie](https://www.npmjs.com/package/cookie)依赖项, 用它解析 cookie 中的昵称

**Comment by Cnotech** [comment]
有截图和昵称示例提供一下吗

**Comment by dsy4567** [comment]
![image](https://user-images.githubusercontent.com/84607814/188258401-571a103d-afdc-4ea4-b004-99b8917392fa.png)
![6{S YZPZD(RSPON3A~YI 5O](https://user-images.githubusercontent.com/84607814/188258478-51fca398-f2d3-4d0b-ac16-4ddbcdd9950c.png)

**Comment by Cnotech** [comment]
> ![image](https://user-images.githubusercontent.com/84607814/188258401-571a103d-afdc-4ea4-b004-99b8917392fa.png) ![6{S YZPZD(RSPON3A~YI 5O](https://user-images.githubusercontent.com/84607814/188258478-51fca398-f2d3-4d0b-ac16-4ddbcdd9950c.png)

昵称在cookie里面的原始值也提供一下

**Comment by dsy4567** [comment]
%E5%87%B3%E5%AD%90%3F
