### ISSUE TITLE
不支持造梦西游、勇者之路这类的游戏吗？

### ISSUE THREAD

**Issue by LawrenceLiuQuanzhou** [Cnotech/flash-collector#14]
像造梦西游、勇者之路、勇士的信仰这类比较大的flash小游戏，是不是不能保存到本地？我倒腾了半天也没成功。

**Comment by Cnotech** [comment]
![image](https://user-images.githubusercontent.com/53827731/188680569-6cec4407-0aed-4441-85e4-27aa8206eed7.png)

造梦西游属于页游本来就不能下载；对于后两个游戏可以给一下链接以便排查问题

**Comment by Cnotech** [comment]
此 issue 长期未回复，且自测在4399搜索勇者之路、勇士的信仰的部分 flash 小游戏可以正常下载，故关闭
