### ISSUE TITLE
这是游戏爬虫，能把H5游戏下载到本地独立运行的吗？

### ISSUE THREAD

**Issue by goople8** [Cnotech/flash-collector#15]
请问这是游戏爬虫吗？是能把H5游戏下载到本地独立运行的吗？
https://kiz10.com/，https://www.crazygames.com/ 这个网站的游戏是否能够抓到呢？

**Comment by Cnotech** [comment]
![image](https://user-images.githubusercontent.com/53827731/205445519-7dce854b-525f-4548-bf98-a1d892ac329f.png)
