### ISSUE TITLE
[bug]: {"errno":-4078,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9222}

### ISSUE THREAD

**Issue by sdtthdsr7u** [Cnotech/flash-collector#16]
### Flash Collector 版本号

1.11.0

### Windows 版本

Windows 10 x64

### 发生什么事了？

源站播放时出现，安了脚本

### 如何复现这个问题？

将游戏的网址导入，下完开嗅探再用源站播放

**Comment by sdtthdsr7u** [comment]
用的是360X64

**Comment by Cnotech** [comment]
描述内容不清晰，请提供截图

**Comment by Cnotech** [comment]
推测是由于嗅探前没有关闭浏览器窗口导致的CDP连接失败，但是此时是会有中文提示要求你关闭浏览器窗口的。此issue长期无回复，故关闭。
![image](https://user-images.githubusercontent.com/53827731/232200027-e397ac39-ffd7-4eb2-ad75-d115bf0d6413.png)
![Snipaste_2023-04-15_16-15-03](https://user-images.githubusercontent.com/53827731/232200033-cbab52b5-1bc1-46bc-815b-e8bd95fb16f0.png)

**Comment by Cnotech** [comment]
追加：可能是由于360浏览器在关闭窗口后仍会在后台运行，导致无法以调试模式启动。需要手动进入任务管理器将其进程杀掉。
