### ISSUE TITLE
[feature]: 允许用户选择使用 Ruffle 运行 Flash 游戏

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#17]
### 有何高见？

如题，https://github.com/ruffle-rs/ruffle

**Comment by Cnotech** [comment]
个人认为ruffle兼容性还是远远比不上原版的flash的，很多游戏没法正常使用，其技术意义大于实用意义，甚至会增加用户的使用困扰，暂不考虑添加
