### ISSUE TITLE
[unsolvable]: 4399“愤怒的小鸟神鹰免费版”无法解析

### ISSUE THREAD

**Issue by Delepha** [Cnotech/flash-collector#18]
### Flash Collector 版本号

1.11.0_win-x64

### Windows 版本

Windows 11 x64

### 无法解析的小游戏页面网址

https://www.4399.com/flash/94107.htm

### 发生什么事了？

![flash-collector_sWrFPd4U94](https://github.com/Cnotech/flash-collector/assets/52903337/c2d38511-3b5a-46c4-8729-9db7d1bb9a86)
这个链接的游戏，“愤怒的小鸟神鹰免费版”，无法解析，但网页打开一切正常（参考下图）
![50wdX88hxQ](https://github.com/Cnotech/flash-collector/assets/52903337/b4f6a729-65bc-4cd2-a8e5-1f34feb16a4f)
由此图可以看出浏览器访问正常（网路等故障已排除）
![flash-collector_mClw6khBvp](https://github.com/Cnotech/flash-collector/assets/52903337/e98b447b-cd29-461b-b07e-595a48aba88f)
此图证明flash-collector一切正常，可以下载其他游戏
PS：已经测试过更换网络环境、更换电脑，该问题均能复现；故推测是不支持解析该页面

### 如何复现这个问题？

输入链接https://www.4399.com/flash/94107.htm
flash-collector无法解析该页面
同一URL，浏览器可以正常访问

不同URL的其他游戏，flash-collector和浏览器均正常访问

故是该页面无法解析

**Comment by Cnotech** [comment]
已在1.12版本修复
