### ISSUE TITLE
parse timeout

### ISSUE THREAD

**Issue by Dawn-Forever** [Cnotech/flash-collector#20]
### Flash Collector 版本号

v1.12

### Windows 版本

Windows 10 x64

### 无法解析的小游戏页面网址

https://www.4399.com/flash/59411_1.htm

### 发生什么事了？

点击下载按钮后出现Error:Parse timeout

### 如何复现这个问题？

复制小游戏网址后 下载转圈一小会提示Error:Parse timeout

**Comment by Cnotech** [comment]
看来下这个游戏是需要联网登录的，因此虽然能解析下载但是在本地是无法正常运行的，请知悉
