### ISSUE TITLE
Windows 10 企业版打开闪退（1.5.0 版本）

### ISSUE THREAD

**Issue by hwangjr** [Cnotech/flash-collector#3]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/2850206/171449212-b2ed3120-3c84-47b5-98fc-c81623b46e55.png">

**Comment by hwangjr** [comment]
本地 yarn dev 的话，会提示  packages/main/schema/config.json 无法找到

**Comment by Cnotech** [comment]
我的`.gitignore`文件写错了，重新pull一下试试

**Comment by Cnotech** [comment]
自测已经没有问题了，作者没有回复故关闭此issue

**Comment by hwangjr** [comment]
H5 有方式可以下载吗。

**Comment by Cnotech** [comment]
没有，智能嗅探对大部分h5都不起作用，chrome的站点保存也没法用

**Comment by Cnotech** [comment]
我也不知道啊毕竟我不是4399的员工，h5游戏很多文件原封不动下下来之后应该还要改一些东西才能用，你可以测试一下
