### ISSUE TITLE
加个深色主题

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#4]
### 有何高见？

能加个深色主题吗, 大半夜用这个眼睛不好受, 谢谢

**Comment by Cnotech** [comment]
这个不算是核心功能，如果想要可以自己实现一下然后发个PR

**Comment by Cnotech** [comment]
如果你觉得很有必要请自己动手提交PR，没有必要在issue里面给我发👎来恶心我，作为一个开发者我没有向你索取任何东西，也没有义务必须满足你提出的所有要求，谢谢。
