### ISSUE TITLE
[bug]: 下载 flash 游戏时提示 Error:Can't fetch game title

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#5]
### Flash Collector 版本号

1.8

### Windows 版本

Windows 11 x64

### 发生什么事了？

下载 https://www.4399.com/flash/18012.htm 时提示 `Error:Can't fetch game title`  
![image](https://user-images.githubusercontent.com/84607814/179438609-b3e50181-a093-4c40-9563-059eb1885dd8.png)

**Comment by Cnotech** [comment]
已提交commit，自测下载 https://www.4399.com/flash/18012.htm 和 https://www.4399.com/flash/48504.htm 配合资源嗅探可以正常运行，可以自己测试一下，如果没问题我稍后发一个新的release。

**Comment by dsy4567** [comment]
好的, 谢谢
