### ISSUE TITLE
在用户尝试下载 h5 页游时给出的错误信息不合适

### ISSUE THREAD

**Issue by dsy4567** [Cnotech/flash-collector#7]
### Flash Collector 版本号

1.9

### Windows 版本

Windows 11 x64

### 发生什么事了？

当我尝试下载 https://www.4399.com/flash/203569.htm 时, 它给出了错误信息`Error:Can't get game category`, 是否可以判断要下载的游戏是不是页游, 然后给出合适的提示

**Comment by Cnotech** [comment]
没有很好的页游判断逻辑，目前唯一的判断依据就是解析出错，但是这个也有可能是程序本身的bug。

因此就改了一下文案，但是感觉比较啰嗦，没有必要：

![image](https://user-images.githubusercontent.com/53827731/181016554-13152592-69db-40d2-8bff-1d91fc504b3d.png)
